CREATE TABLE
FRAME$FRAME
(
TOPIC_ID INTEGER(11) NOT NULL,
START_POSITION INTEGER(11) NOT NULL,
END_POSITION INTEGER(11) NOT NULL,
START_TERM_ID INTEGER(11) NOT NULL,
END_TERM_ID INTEGER(11) NOT NULL,
NUMBER_OF_FRAME_OCCURRENCES INTEGER(11) NOT NULL,
NUMBER_OF_DOCUMENTS INTEGER(11) NOT NULL
) ENGINE INNODB