CREATE TABLE CORPUS_${corpus}_TEXT (
    DOCUMENT_ID    INTEGER(11) NOT NULL,
    DOCUMENT_TEXT  MEDIUMTEXT CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT DOCUMENT_ID_PK PRIMARY KEY ( DOCUMENT_ID )
    )
    ENGINE = ARIA DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin,
    TRANSACTIONAL = 1,
    COMMENT = 'text data of corpus'
;
